# config/meta.yml

meta_product_name: CodeBank

meta_title: CodeBank – Save your code, Save your time

meta_description: With CodeBank, you can effortlessly store your code snippets and organize them into directories.
This platform is 100% free and designed by developers for developers.
Don't hesitate for a moment – sign in now and take your coding experience to the next level!

meta_image: meta_image.png # should exist in `app/assets/images/`

twitter_account: “” # required for Twitter Cards
